languageCode = "en"
languageName = "English"
weight = 1
title = "partkyle.dev"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2006 January 2"
description = "just stuff about me"

[author]
name = "partkyle"
headline = "i do stuff and things"
